#!/bin/bash
#
# JILT launcher script for Linux.
# This version of the launcher is suitable for those developing with IntelliJ.
# For a version included in a release see resources/jilt

dir="$(dirname "$0")"
export CLASSPATH="${dir}/out/production/jilt"

java -Dlists.dir="${dir}/lists" irvine.jilt.Jilt "$@"
